### ISSUE TITLE
Upload failure on CircleCI

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/gmpy2-feedstock#1]
So, this is a fun issue. Looks like it failed to upload. Seems like an `anaconda-client` issue ( https://github.com/Anaconda-Platform/anaconda-client/issues/335 ) cropped up after some sort of failure to upload. See this [log](https://circleci.com/gh/conda-forge/gmpy2-feedstock/1) and the traceback below.

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/commands/upload.py", line 214, in main
    callback=upload_print_callback(args))
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/__init__.py", line 500, in upload
    raise errors.BinstarError('Error uploading package', s3res.status_code)
binstar_client.errors.BinstarError: ('Error uploading package', 500)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/anaconda", line 6, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 87, in main
    description=__doc__, version=version)
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
    return args.main(args)
  File "/opt/conda/lib/python3.5/site-packages/binstar_client/commands/upload.py", line 219, in main
    except requests_ext.OpenSslError:
TypeError: catching classes that do not inherit from BaseException is not allowed
Traceback (most recent call last):
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 124, in <module>
    main()
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 108, in main
    upload(cli, meta, owner, channel)
  File "/feedstock_root/ci_support/upload_or_check_non_existence.py", line 55, in upload
    env=os.environ)
  File "/opt/conda/lib/python3.5/subprocess.py", line 584, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', 'binstar.token', 'upload', '/feedstock_root/build_artefacts/linux-64/gmpy2-2.0.7-py34_0.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1
```

cc @pelson

**Comment by jakirkham** [comment]
Going to try restarting the build to see if this wasn't a fluke.

**Comment by jakirkham** [comment]
Sure enough. Restarting fixed the issue. Closing...
